from datetime import datetime, timezone
from typing import List, Dict, Any, Optional

class ExecutionPlan:
    """
    Structured Execution Plan generated by AgentPlanner for VARTA AI Assistant.
    Defines the plan type, step-by-step retrieval operations, and reasoning before RAG execution.
    """

    SUPPORTED_PLAN_TYPES = {
        "direct", "followup", "comparison", "multi_step", "summarization",
        "clarification", "calculator", "system_info", "conversation_memory", "document_search"
    }

    def __init__(
        self,
        plan_type: str,
        steps: List[Dict[str, Any]],
        original_query: str,
        rewritten_query: str,
        reasoning: str = ""
    ):
        self.plan_type: str = plan_type if plan_type in self.SUPPORTED_PLAN_TYPES else "direct"
        self.steps: List[Dict[str, Any]] = steps
        self.original_query: str = original_query
        self.rewritten_query: str = rewritten_query
        self.reasoning: str = reasoning
        self.created_at: str = datetime.now(timezone.utc).isoformat()

    def get_retrieval_steps(self) -> List[Dict[str, Any]]:
        """Returns only the steps of type 'retrieve'."""
        return [step for step in self.steps if step.get("type") == "retrieve"]

    def summary_str(self) -> str:
        """Returns a human-readable string summary of the execution plan."""
        lines = [f"Execution Plan [{self.plan_type}]:"]
        for idx, step in enumerate(self.steps, 1):
            stype = step.get("type", "unknown")
            if stype == "retrieve":
                lines.append(f"  {idx}. Retrieve: \"{step.get('query', '')}\"")
            elif stype == "compare":
                lines.append(f"  {idx}. Compare & Synthesize")
            elif stype == "summarize":
                lines.append(f"  {idx}. Summarize Assembled Context")
            elif stype == "clarify":
                lines.append(f"  {idx}. Request User Clarification")
            else:
                lines.append(f"  {idx}. Step: {stype}")
        return "\n".join(lines)

    def to_dict(self) -> Dict[str, Any]:
        """Serializes ExecutionPlan to a dictionary."""
        return {
            "plan_type": self.plan_type,
            "steps": self.steps,
            "original_query": self.original_query,
            "rewritten_query": self.rewritten_query,
            "reasoning": self.reasoning,
            "created_at": self.created_at
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ExecutionPlan":
        """Deserializes dictionary into an ExecutionPlan object."""
        plan = cls(
            plan_type=data.get("plan_type", "direct"),
            steps=data.get("steps", []),
            original_query=data.get("original_query", ""),
            rewritten_query=data.get("rewritten_query", ""),
            reasoning=data.get("reasoning", "")
        )
        if "created_at" in data:
            plan.created_at = data["created_at"]
        return plan
