from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    """Request model for /chat endpoint."""
    message: str = Field(..., min_length=1, description="User question or input message.")
    session_id: Optional[str] = Field(None, description="Optional active session ID. Created automatically if omitted.")

class ChatResponse(BaseModel):
    """Response model for /chat endpoint."""
    session_id: str = Field(..., description="Active session ID for the conversation turn.")
    answer: str = Field(..., description="Grounded response synthesized by VARTA.")
    citations: List[Dict[str, Any]] = Field(default_factory=list, description="List of source citations.")
    confidence: Dict[str, Any] = Field(default_factory=dict, description="Confidence metrics.")
    execution_time_ms: float = Field(..., description="Total pipeline latency in milliseconds.")
    tool_used: str = Field(..., description="Name of tool invoked by the planner.")
    plan_type: str = Field(..., description="Plan type generated by AgentPlanner.")

class SessionCreateResponse(BaseModel):
    """Response model for session creation."""
    session_id: str = Field(..., description="Newly created unique session ID.")

class SessionEndResponse(BaseModel):
    """Response model for session termination."""
    session_id: str = Field(..., description="Terminated session ID.")
    message: str = Field(..., description="Status message confirming closure.")

class HealthResponse(BaseModel):
    """Response model for health check endpoint."""
    status: str = Field(..., description="API operational status (e.g. 'ok').")
    api_version: str = Field(..., description="Current REST API semantic version.")
    uptime_seconds: float = Field(..., description="Server uptime in seconds.")
    active_model: str = Field(..., description="LLM model name.")
    provider: str = Field(..., description="LLM provider name.")

class SystemInfoResponse(BaseModel):
    """Response model for system information endpoint."""
    active_model: str = Field(..., description="Active LLM model.")
    provider: str = Field(..., description="LLM adapter provider.")
    vector_db_status: str = Field(..., description="Status of indexed vector database.")
    active_sessions: int = Field(..., description="Count of currently active sessions.")
    tool_count: int = Field(..., description="Count of registered tools in ToolRegistry.")
    build_version: str = Field(..., description="VARTA system build version.")

class ErrorResponse(BaseModel):
    """Standardized error response payload."""
    detail: str = Field(..., description="Human-readable error explanation.")
    error_code: Optional[str] = Field(None, description="Categorical error code.")

class DatasetIngestResponse(BaseModel):
    """Response model for dataset upload and ingestion endpoint."""
    status: str = Field(..., description="Ingestion status ('ready' or 'failed').")
    message: str = Field(..., description="Human-friendly message summarizing ingestion result.")
    filename: str = Field(..., description="Original filename of the uploaded dataset.")
    documents_ingested: int = Field(..., description="Number of documents successfully processed and standardized.")
    chunks_indexed: int = Field(..., description="Number of semantic vector chunks indexed.")
    total_vectors_available: int = Field(..., description="Total vector records available in vector database.")
    duration_sec: float = Field(..., description="Total ingestion and embedding duration in seconds.")

class ReviewDecisionRequest(BaseModel):
    """Request model for submitting Sagar's review decision for a specific context."""
    record_id: str = Field(..., description="Unique ID of the record being reviewed.")
    decision: str = Field(..., description="Decision: 'KEEP' or 'EXCLUDE'.")
    context_topic: Optional[str] = Field(default="Floods in Assam", description="Active research context topic for this decision.")

class ReviewRecordItem(BaseModel):
    """Schema for a single record in the Sagar review queue."""
    record_id: str
    title: str
    content_preview: str
    relevance_score: float
    matched_keywords: str
    relevance_reason: str
    final_decision: str
    context_topic: str = "Floods in Assam"

class ReviewQueueResponse(BaseModel):
    """Response model for review queue listing."""
    context_topic: str = "Floods in Assam"
    total_records: int
    reviewed_count: int
    pending_count: int
    keep_count: int
    exclude_count: int
    records: List[ReviewRecordItem]
