from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    """Request model for /chat endpoint."""
    message: str = Field(..., min_length=1, description="User question or input message.")
    session_id: Optional[str] = Field(None, description="Optional active session ID. Created automatically if omitted.")
    dataset_filter: Optional[List[str]] = Field(None, description="Optional list of source_dataset values to scope retrieval.")

class DatasetItem(BaseModel):
    """Metadata item for an indexed dataset."""
    source_dataset: str = Field(..., description="Unique raw source_dataset identifier/tag.")
    display_name: str = Field(..., description="Formatted user-friendly display name.")
    chunk_count: int = Field(..., description="Total number of chunks indexed for this dataset.")

class DatasetListResponse(BaseModel):
    """Response model for /datasets/list endpoint."""
    datasets: List[DatasetItem] = Field(default_factory=list, description="List of available datasets.")
    total_datasets: int = Field(..., description="Total number of distinct datasets.")
    total_chunks: int = Field(..., description="Total chunks across all datasets.")

class ChatResponse(BaseModel):
    """Response model for /chat endpoint."""
    session_id: str = Field(..., description="Active session ID for the conversation turn.")
    answer: str = Field(..., description="Grounded response synthesized by VARTA.")
    citations: List[Dict[str, Any]] = Field(default_factory=list, description="List of source citations.")
    confidence: Dict[str, Any] = Field(default_factory=dict, description="Confidence metrics.")
    execution_time_ms: float = Field(..., description="Total pipeline latency in milliseconds.")
    tool_used: str = Field(..., description="Name of tool invoked by the planner.")
    plan_type: str = Field(..., description="Plan type generated by AgentPlanner.")

class SessionCreateResponse(BaseModel):
    """Response model for session creation."""
    session_id: str = Field(..., description="Newly created unique session ID.")

class SessionEndResponse(BaseModel):
    """Response model for session termination."""
    session_id: str = Field(..., description="Terminated session ID.")
    message: str = Field(..., description="Status message confirming closure.")

class HealthResponse(BaseModel):
    """Response model for health check endpoint."""
    status: str = Field(..., description="API operational status (e.g. 'ok').")
    api_version: str = Field(..., description="Current REST API semantic version.")
    uptime_seconds: float = Field(..., description="Server uptime in seconds.")
    active_model: str = Field(..., description="LLM model name.")
    provider: str = Field(..., description="LLM provider name.")

class SystemInfoResponse(BaseModel):
    """Response model for system information endpoint."""
    active_model: str = Field(..., description="Active LLM model.")
    provider: str = Field(..., description="LLM adapter provider.")
    vector_db_status: str = Field(..., description="Status of indexed vector database.")
    active_sessions: int = Field(..., description="Count of currently active sessions.")
    tool_count: int = Field(..., description="Count of registered tools in ToolRegistry.")
    build_version: str = Field(..., description="VARTA system build version.")

class ErrorResponse(BaseModel):
    """Standardized error response payload."""
    detail: str = Field(..., description="Human-readable error explanation.")
    error_code: Optional[str] = Field(None, description="Categorical error code.")

class DatasetIngestResponse(BaseModel):
    """Response model for dataset upload and ingestion endpoint."""
    status: str = Field(..., description="Ingestion status ('ready' or 'failed').")
    message: str = Field(..., description="Human-friendly message summarizing ingestion result.")
    filename: str = Field(..., description="Original filename of the uploaded dataset.")
    documents_ingested: int = Field(..., description="Number of documents successfully processed and standardized.")
    chunks_indexed: int = Field(..., description="Number of semantic vector chunks indexed.")
    total_vectors_available: int = Field(..., description="Total vector records available in vector database.")
    duration_sec: float = Field(..., description="Total ingestion and embedding duration in seconds.")

class ReviewDecisionRequest(BaseModel):
    """Request model for submitting Sagar's review decision for a specific context."""
    record_id: str = Field(..., description="Unique ID of the record being reviewed.")
    decision: str = Field(..., description="Decision: 'KEEP' or 'EXCLUDE'.")
    session_id: Optional[str] = Field(default=None, description="Optional active session ID.")
    context_topic: Optional[str] = Field(default=None, description="Active research context topic for this decision.")

class ReviewRecordItem(BaseModel):
    """Schema for a single record in the Sagar review queue."""
    record_id: str
    title: str
    content_preview: str
    relevance_score: float
    matched_keywords: str
    relevance_reason: str
    final_decision: str
    context_topic: str = ""

class PreprocessingStageInfo(BaseModel):
    """Details of a single preprocessing transformation stage."""
    stage_number: int
    stage_name: str
    description: str
    status: str = "COMPLETED"
    details: str = ""

class DatasetAuditStats(BaseModel):
    """Dataset quality and transformation audit summary for stakeholder."""
    total_master_records: int = 0
    auto_kept_count: int = 0
    auto_excluded_count: int = 0
    borderline_review_count: int = 0
    quality_status: str = "HEALTHY & INDEXED"
    summary_message: str = ""
    languages: Dict[str, int] = Field(default_factory=lambda: {"English": 0, "Hindi": 0})
    deduplication_rate_pct: float = 0.0
    vector_index_status: str = "SYNCHRONIZED (384-dim)"
    available_regions: List[str] = Field(default_factory=lambda: ["All Corpus", "Assam", "Mumbai", "Bihar", "Odisha", "Gorakhpur", "Sikkim"])
    preprocessing_stages: List[PreprocessingStageInfo] = Field(default_factory=list)

class ReviewQueueResponse(BaseModel):
    """Response model for review queue listing and dataset audit."""
    context_topic: str = ""
    session_id: Optional[str] = None
    audit_stats: Optional[DatasetAuditStats] = None
    total_records: int = 0
    reviewed_count: int = 0
    pending_count: int = 0
    keep_count: int = 0
    exclude_count: int = 0
    records: List[ReviewRecordItem] = []

